import { computeSmoothNormals, type MeshGeometry, type SubMesh } from '@/core/mesh';
import type { TankBounds } from '@/embodiment/types';

/**
 * The research tank.
 *
 * A dark dish with a floor and four low walls - deliberately not an aquarium.
 * Its purpose is to give the organism a boundary it can actually sense and
 * collide with, and to give the eye a ground plane so motion is legible.
 */
export function buildTank(bounds: TankBounds, scale: number): MeshGeometry {
  const hw = bounds.halfWidth * scale;
  const hd = bounds.halfDepth * scale;
  const floor = (-bounds.height / 2) * scale;
  const top = (bounds.height / 2) * scale;

  const positions: number[] = [];
  const indices: number[] = [];

  const quad = (
    a: readonly [number, number, number],
    b: readonly [number, number, number],
    c: readonly [number, number, number],
    d: readonly [number, number, number],
  ) => {
    const base = positions.length / 3;
    positions.push(...a, ...b, ...c, ...d);
    indices.push(base, base + 1, base + 2, base, base + 2, base + 3);
  };

  // Floor.
  quad([-hw, floor, -hd], [hw, floor, -hd], [hw, floor, hd], [-hw, floor, hd]);
  // Four walls, wound so their outward faces point away from the water.
  quad([-hw, floor, -hd], [-hw, top, -hd], [hw, top, -hd], [hw, floor, -hd]);
  quad([hw, floor, hd], [hw, top, hd], [-hw, top, hd], [-hw, floor, hd]);
  quad([-hw, floor, hd], [-hw, top, hd], [-hw, top, -hd], [-hw, floor, -hd]);
  quad([hw, floor, -hd], [hw, top, -hd], [hw, top, hd], [hw, floor, hd]);

  const positionsArray = new Float32Array(positions);
  const indicesArray = new Uint32Array(indices);
  const subMeshes: SubMesh[] = [
    { name: 'tank', material: 'environment', indexOffset: 0, indexCount: indicesArray.length },
  ];

  return {
    name: 'tank',
    vertexCount: positionsArray.length / 3,
    indexCount: indicesArray.length,
    positions: positionsArray,
    normals: computeSmoothNormals(positionsArray, indicesArray),
    indices: indicesArray,
    subMeshes,
    bones: [],
    boundsUm: { min: [-hw, floor, -hd], max: [hw, top, hd] },
    space: 'world',
    sourceAttribution: 'Generated environment geometry.',
    license: 'Generated by this project.',
  };
}
